---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mastodon-get-replies
spec:
  # Run every 2 hours
  schedule: "0 */2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mastodon-get-replies
              image: ghcr.io/nanos/mastodon_get_replies:latest
              args:
                - --server=your.server.social
                - --access-token=TOKEN
          restartPolicy: Never

