name: getContext

on:
  workflow_dispatch
  # schedule:
  #    - cron: '0 0 * * *'
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
         python-version: '3.10' 
         cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Download all workflow run artifacts
        uses: dawidd6/action-download-artifact@v2
        with: 
          name: artifacts
      - name: Display structure of downloaded files
        if: always()
        run: ls -R
      - run: python get_context.py ${{ secrets.ACCESS_TOKEN }} mstdn.thms.uk 1 1
        if: always()
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            artifacts
