name: getAllRepliesToKnownPots

on:
  workflow_dispatch:
  schedule:
     - cron: '*/15 * * * *'
  
jobs:
  run:
    runs-on: ubuntu-latest
    environment: mastodon
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
         python-version: '3.10' 
         cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Download all workflow run artifacts
        uses: dawidd6/action-download-artifact@v2
        with: 
          name: artifacts
          workflow: get_context.yml
          if_no_artifact_found: warn
          path: artifacts
      - run: python get_context.py ${{ secrets.ACCESS_TOKEN }} ${{ vars.MASTODON_SERVER }} ${{ vars.REPLY_INTERVAL_IN_HOURS }} ${{ vars.HOME_TIMELINE_LENGTH }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            artifacts
